### ISSUE TITLE
Exception is thrown while registering assembly classes on AddWeapsyCqrs method in startup

### ISSUE THREAD

**Issue by siematypie** [OpenCQRS/OpenCQRS#24]
Hi, 
I'm having problem with following class from my domain project

```
public class BaseVenueValidator<T> : AbstractValidator<T> where T : BaseVenueCommand
    {
        private readonly IVenueRules _venueRules;

        public BaseVenueValidator(IVenueRules venueRules)
        {
            _venueRules = venueRules;

            RuleFor(c => c.VenueId)
                .NotEmpty().WithMessage("Brak Id Lokalu!")
                .Must(BeAnExistingVenue).WithMessage("Lokal nie istnieje w bazie!");
        }

        private bool BeAnExistingVenue(Guid venueId)
        {
            return _venueRules.DoesVenueExist(venueId);
        }
    }

```
and the baseValueCommand class:

`    public class BaseVenueCommand: DomainCommand
    {
        public Guid VenueId { get; set; }
    }
`
I'm using AbstractValidator from FluentValidation. I'm getting following exception on application startup: `'Gastro.Domain.BaseVenueValidator`1[T]' violates the constraint of type parameter 'T'`.
I guess there's some problem with scurtors register as implemented interfaces method that you are using in addWeapsyCqrs method. Is it possible to somehow fix this issue? I'm using dotnet core 2.1 and latest version of WeapsyCqrs

**Comment by lucabriguglia** [comment]
Hi, if you are using a package called Weapsy.Cqrs you should uninstall it and install the OpenCQRS.

**Comment by siematypie** [comment]
Just finished doing it, error is still there :(

**Comment by lucabriguglia** [comment]
It should be BaseVenueValidator : AbstractValidator<BaseVenueCommand> if it's not an abstract class.
I haven't tested it because I'm writing from my mobile, but it should fix it.

**Comment by lucabriguglia** [comment]
Hi, I'm glad that you like the project and that's useful for you :-) and good luck for your thesis!
