### ISSUE TITLE
Example of using OpenCQRS using a NetCore 2 command line console app?

### ISSUE THREAD

**Issue by kbarkhausen** [OpenCQRS/OpenCQRS#27]
Do you have an example of using OpenCQRS using console app? I have been trying to put on example together but I notice that I get an error since OpenCQRS wants to access an instance of the IHttpContextAccessor to access the publisher. Any idea how I can set up OpenCQRS in a console app to execute commands and publish any events?

**Comment by lucabriguglia** [comment]
I'm treating this as a bug as it was a mistake the use of IHttpContextAccessor instead of IServiceProvider to resolve the handlers.
Once fixed, I'll published an example of a console app.
Thanks.

**Comment by kbarkhausen** [comment]
I am trying to learn how to properly use the OpenCQRS framework. I am creating a Console App that uses commands and events. I was able to override the Resolver using my own that uses the Net Core ServiceProvider. I did use AutoFac to improve the DI implementation. I can add this into your examples once I get it fully working (if this ineterests you). My console app does not use AggregateRoot or Event sourcing - just commands, events and the dispatcher. Maybe you want to review it and improve how I used the framework.

**Comment by lucabriguglia** [comment]
Yes that would be really interesting, thanks! Bear in mind that I'm removing the examples from the main repository as I'm going to create a separate one for each of them.
You could create a separate repository with your fully working version and post the link here.

**Comment by kbarkhausen** [comment]
Hey, Luca. I created an example console app that uses OpenCQRS. I am not sure if I am using the framework correctly so I would be interested in your suggestions. It may be a good example to help others learn how to use it. Source: [OpenCqrs Command Line Interface](https://github.com/kbarkhausen/OpenCqrsCli)

**Comment by lucabriguglia** [comment]
Hi Klaus, I'll have a look as soon as I can.
I'll also create a new section in the wiki with examples from other developers.

**Comment by kbarkhausen** [comment]
Luca thanks for the comments. I do have a major problem that maybe you can clarify in your framework. How would I unit test the command handlers? The command that implements ICommandHandlerWithEventsAsync<CreateCommand> does not provide access to the method that implements the logic in the command which is: async Task<IEnumerable<IEvent>> ICommandHandlerWithEventsAsync<CreateCommand>.HandleAsync(CreateCommand command).

Today's market demands fully tested code. Without the capability of unit testing, any framework would be useless. Any suggestions?

**Comment by kbarkhausen** [comment]
Disregard my previous message. I am able to fully test command and event handlers. I will update my project with unit tests shortly. It should provide a good base for starting to learn to use the framework for creating commands and/or CLI apps.

**Comment by lucabriguglia** [comment]
Great news! Any queries/comments are more than welcome :-)
And please let me know if you have any suggestions on how I can improve the documentation for the framework.

**Comment by lucabriguglia** [comment]
Closing this issue, #35 will be used instead.
