### ISSUE TITLE
IDomainCommand.ExpectedVersion

### ISSUE THREAD

**Issue by corfor** [OpenCQRS/OpenCQRS#28]
This would be helpful in addressing situations that could have race conditions. This way the command handler can check if the aggregate has changed since the time the command was issued by the client.

`int ExpectedVersion { get; }`

**Comment by lucabriguglia** [comment]
I was thinking about this feature for a long time.
I'll add it in one of the next versions, probably 5.2.

**Comment by lucabriguglia** [comment]
It will be nullable

**Comment by lucabriguglia** [comment]
I think it makes more sense to add an "OriginalVersion" instead of "ExpectedVersion" because an expected version implies a calculation that should be done in the event store not at the command level.

**Comment by corfor** [comment]
I'd suggest that ExpectedVersion matches the usual semantics I've seen in various CQRS projects I've done or have seen in the wild. For me, calling it OriginalVersion would be increased friction.

The intended use case, as I've thought of it anyway, is for a CommandHandler to compare the 'command.ExpectedVersion' with the 'aggregate.Version'. If they don't line up, it means the aggregate has changed since the command was issued, and appropriate action should be taken per business rules.

**Comment by lucabriguglia** [comment]
Okay, I got your point and I can see 2 possible scenarios.
1) You need to take an appropriate action based on your business rules. In this case you might need the "ExpectedVersion" and the command handler should manage the exception.
2) You NOT need to take any actions, just throw a concurrency exception if needed. In this case you might just need an "OriginalVersion" and let the framework handle the validation and the exception for you.

**Comment by lucabriguglia** [comment]
Released
