### ISSUE TITLE
Question: How event faults are processed

### ISSUE THREAD

**Issue by pblachut** [OpenCQRS/OpenCQRS#29]
This is a question rather than issue.

As far as I was able to read from the source code, when the events are produced by the aggregate then they are saved in event store and published by the event publisher:

```csharp
public void SendAndPublish<TCommand, TAggregate>(TCommand command) 
            where TCommand : IDomainCommand 
            where TAggregate : IAggregateRoot
        {
            if (command == null)
                throw new ArgumentNullException(nameof(command));

            var handler = _handlerResolver.ResolveHandler<ICommandHandlerWithDomainEvents<TCommand>>();

            _commandStore.SaveCommand<TAggregate>(command);

            var events = handler.Handle(command);

            foreach (var @event in events)
            {
                @event.CommandId = command.Id;
                var concreteEvent = _eventFactory.CreateConcreteEvent(@event);
                _eventStore.SaveEvent<TAggregate>((IDomainEvent)concreteEvent);
                _eventPublisher.Publish(concreteEvent);
            }
        }
```

This comes to me with an conclusion that there is no transaction during saving these events to the event store either publishing then on the bus / updating read model. 
When save of single event will fail then save of previous ones will not be compensated. Similar situstion os without read model. Can you confirm that?

**Comment by lucabriguglia** [comment]
You are right, there is no transaction for the events.
But the possibility of having more than one event as a result of a command handler is very low.
I decided to have a list of domain events as result just to give the framework more flexibilty.
Also, it would be something not support by all data providers.
Regarding the read model, if you want it to be immediately consistent you could save it in the command handler along with the write model using the same transaction.

**Comment by lucabriguglia** [comment]
As System.Transactions is now supported in EF Core 2.1, I'll add support to transactions.

**Comment by lucabriguglia** [comment]
Closing this issue as I've created a new issue #35 for transactions support.
