### ISSUE TITLE
[Idea] Simplify dispatcher - Make callee responsible it's actions

### ISSUE THREAD

**Issue by andreujuanc** [OpenCQRS/OpenCQRS#33]
Hello, 

This idea might be really hard to implement: **what if IDispatcher were simpler**?

There are basically 4 flavours for the dispatcher to dispatch a ICommand:

- Simple ICommand
- Simple IDomainCommand
- ICommand with Events
- IDomainCommand with Events

In this case, the person who is executing the action has to know exactly what to use regarding the actual actual implementation of the command.  

We could make HandlerResolver, CommandSender, etc, smarter about this, so that it knows what to call based on the command's interfaces?

More over: should the caller dedice if the Events are published or not?
So `SendAndPublishAsync `should be a thing? or should it be based on wether the the handler implementation task returns events?

I will try to create a "demo" of this, to get the feel for it in my fork. Will post link if idea seems duable/reasonable.

PS: Feel free to close this issue if it goes beyond the scope of this project.

Cheers.

**Comment by andreujuanc** [comment]
Here it is:
https://github.com/andreujuanc/OpenCQRS/blob/simplifyDispatcher/src/OpenCqrs/Commands/CommandSender.cs#L41

**Comment by lucabriguglia** [comment]
I like the idea of making commands responsible of the aggregate root definition and I would like to do the same for queries/results.
I'm not so sure about the implementation in the command sender tough, I'll give it a try in the next few days.

**Comment by lucabriguglia** [comment]
Based on your suggestion I'm adding a new global option and a property to the IEvent interface in order to decide if publish the event or not. You can follow the progress in the dev branch: https://github.com/OpenCQRS/OpenCQRS/tree/Dev

**Comment by andreujuanc** [comment]
Great! will take a look a it!

**Comment by lucabriguglia** [comment]
Thanks @andreujuanc

**Comment by lucabriguglia** [comment]
Breaking changes here: https://github.com/OpenCQRS/OpenCQRS/releases
