### ISSUE TITLE
Where should be placed business logic?

### ISSUE THREAD

**Issue by Ilchuk-Mihail** [OpenCQRS/OpenCQRS#45]
If I placed this confidential logic in command handler.  This data also writes in event store,  table DomainCommand. 

It should be additional layer for all logic (some services), and Commands/Events only updates storages ?

**Comment by lucabriguglia** [comment]
I put the business logic in the handler itself and in the aggregate. Everything related to event sourcing happens under the hood. Command handlers are the equivalent of buissness services in a layered architecture.

**Comment by Ilchuk-Mihail** [comment]
Yes, but if I need works with some confidential data (some encryption data, etc). 
So, if I do it in commands it's data writes to DomainCommands table in not encrypted format.

Also, If I need to do some manipulation with data, and return result from command, not store it.

**Comment by Ilchuk-Mihail** [comment]
Some another questions: Could I do some commands in background ?
I did make hangfire (fire and forget job), but nothing happened. For command/events execution needs context ?

**Comment by Ilchuk-Mihail** [comment]
error in background execution

System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenCqrs.Dependencies.Resolver.Resolve[T]()
   at OpenCqrs.Dependencies.HandlerResolver.ResolveHandler[THandler]()
   at OpenCqrs.Queries.QueryProcessor.ProcessAsync[TQuery,TResult](TQuery query)

**Comment by lucabriguglia** [comment]
These are two options I could add, not store the commands and return a result.

**Comment by lucabriguglia** [comment]
Hi @Ilchuk-Mihail, sorry for the delay, tough time between work and uni :-)
I'm trying to find the best way to add a configuration option for saving commands at the global level and at the command level.
Not sure about returning results for the commands. Ideally commands should not return anything, but maybe it might be useful to return the event(s) generated.

**Comment by lucabriguglia** [comment]
Doing some experiments in the dev branch: https://github.com/OpenCQRS/OpenCQRS/tree/Dev

**Comment by lucabriguglia** [comment]
I have added global configuration options that can be set during registration (default value is true):
```C#
services
  .AddOpenCqrs(typeof(CreateProduct), typeof(GetProduct))
  .AddOptions(x => { x.SaveCommands = false; })
  .AddSqlServerProvider(Configuration)
  .AddServiceBusProvider(Configuration);
```
and the default setting can be overridden for every command using the new property SaveCommand of the IDomainCommand interface:
```C#
public interface IDomainCommand : ICommand
{
    Guid Id { get; set; }
    Guid AggregateRootId { get; set; }
    string UserId { get; set; }
    string Source { get; set; }
    DateTime TimeStamp { get; set; }
    int? ExpectedVersion { get; set; }
    bool? SaveCommand { get; set; }
}
```

**Comment by andreujuanc** [comment]
Maybe he meant to do this in a by-command basis? and not for the whole app?

```csharp
[SaveCommand(false)]
public class CreateProduct : DomainCommand
```

```csharp
[UnpersistedCommand]
public class CreateProduct : DomainCommand
```

```csharp
public class CreateProduct : UnpersistedDomainCommand
```

Or similar approaches.

TIL: https://en.wiktionary.org/wiki/unpersist

**Comment by lucabriguglia** [comment]
You can set it for the whole app and still be able to override it on a command basis by simply override the property SaveCommand

**Comment by andreujuanc** [comment]
Great!

**Comment by lucabriguglia** [comment]
I'm wondering if it might be better to still save the command but not the data associated to it.

**Comment by Ilchuk-Mihail** [comment]
@lucabriguglia 
Thanks for help. 

> I'm wondering if it might be better to still save the command but not the data associated to it.
In my opinion, it is a better way. That way we can track all events and commands which happened in the app. We will not have any gaps.

**Comment by lucabriguglia** [comment]
> @lucabriguglia
> Thanks for help.
> 
> I'm wondering if it might be better to still save the command but not the data associated to it.
> 
> In my opinion, it is a better way. That way we can track all events and commands which happened in the app. We will not have any gaps.

I agree, I would change the SaveCommand property to SaveCommandData.

**Comment by lucabriguglia** [comment]
Commit here: https://github.com/OpenCQRS/OpenCQRS/commit/473cb1b72a0815a82f7573a65d860e123dc582e3
