### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by irperez** [OpenCQRS/OpenCQRS#53]
I love what you guys have done with this project.  However, due to it being licensed as GPL, our company cannot adopt this into our software.  I wish it was licensed as MIT or Apache.

Just an FYI.  I'm probably not alone in this camp.

**Comment by lucabriguglia** [comment]
Hi @irperez, thanks for the information. You are the first one to raise this problem but I'll have a look at other licenses.

**Comment by lucabriguglia** [comment]
I might opt for Apache 2.0 because you are right as per the nature of this project it would make more sense.

**Comment by lucabriguglia** [comment]
License changed to Apache 2.0. Thanks @irperez

**Comment by lucabriguglia** [comment]
@irperez please let me know if I can help you in any way with using the the framework.

**Comment by irperez** [comment]
Thank you @lucabriguglia.

With this license change, we can have a much more serious look at it thank you for that!

**Comment by lucabriguglia** [comment]
@irperez happy to help :-)
